#!/bin/sh
# Run setup first to setup cli

function log_wrapper() {
    printf "[exe] %s\n" $1
}

function check_setup () {
    if [ ! -e "cache.leo" ];
    then
        log_wrapper "Setting up"
        echo "alias exe='./exe'" >> ~/.bashrc
        echo "alias exe='./exe'" >> ~/.zshrc
        echo "hit=1" > ./cache.leo # always replace
    fi
}

check_setup
log_wrapper "Compiling"
gcc main.c -o out
log_wrapper "Executing"
./out
